frontend/package-lock.json
frontend/package.json

Update Next to 9.3 along with it's dependency upgrades! 🙌🏼

Update to Next 9.3

---

backend/package-lock.json
backend/package.json

Upgrade Prisma2 to latest release.

Upgrade Prisma2 to release 24

---

frontend/package-lock.json

Fix the recent security vulnerability notice re: `minimist` (dependency of Next).

Fix Minimist Security Vulnerability

---

docs/approach-docs/system-svg.md

**Issue:** #55 
Approach doc to Design & Implement a system for using SVGs at Journaly.

Approach Doc - Design & Implement a system for using SVGs at Journaly

---

frontend/components/LoginForm/LoginForm.tsx
frontend/elements/Button/Button.tsx
frontend/package-lock.json
frontend/package.json

**Issue:** #70 
This is the POC for using `react-hook-form`. It's actually one of the most pleasant experiences integrating a form library that I've ever had 😌 Every single thing I wanted to do, I found in the docs, complete with multiple examples and codepens!

Implement LoginForm with react-hook-form

---

frontend/components/JournalyEditor/Button.tsx
frontend/components/JournalyEditor/JournalyEditor.tsx
frontend/styles/reset.css
frontend/theme/index.ts

**Issue:** #75 
🚨 No visual changes, just code refactoring

Clean up the text editor for writing a new post

---

backend/package-lock.json
backend/package.json
backend/src/graphql.ts

To be fair the docs were lying to me in turn.
Can actually query from the big blue screen at localhost:4000 now

I lied in the last PR

---

backend/seed.ts

Fixed seed data so it will load, issues were field casing, apparently changed API around nested writes, and `language` being a mandatory field.

Fixed seed data.

---

frontend/components/Dashboard/Post/Post.tsx
frontend/components/InlineFeedbackPopover/index.tsx
frontend/generated/graphql.tsx
frontend/graphql/postById.graphql

Display thread/comments when clicking on a comment. Not super pretty, but functional

Display inline feedback

---

backend/seed.ts
backend/src/graphql.ts
backend/tsconfig.json

**Issue:** #107 
Our "My Feed" page needs to be bold and robust with superb searching and filtering capabilities and good pagination.
This PR implements this functionality!
Also fixes our backend `.tsconfig.json` file finally :)

Implement My Feed Search, Filtering, and Pagination - Backend

---

backend/src/graphql.ts
backend/src/utils.ts
frontend/components/Dashboard/Nav/Nav.tsx
frontend/components/JournalyEditor/JournalyEditor.tsx
frontend/components/LanguageSelect/index.tsx
frontend/generated/graphql.tsx
frontend/graphql/createPost.graphql
frontend/graphql/currentUser.graphql
frontend/lib/apollo.tsx
frontend/pages/dashboard/new-post.tsx

- Generate excerpt when a post is created
- FE and BE for setting the language a post is in
- Made new post page less hideous
Also fixed issue were we had to refetch the currentUser query (or any query relying on cookies) in a `useEffect`

A few things around post creation

---

cypress.json
cypress/fixtures/example.json
cypress/integration/landing/explore_landing_page.spec.js
cypress/integration/posts/new_post.spec.js
cypress/integration/smoke_test.spec.js
cypress/integration/user/login.spec.js
cypress/integration/user/signup.spec.js
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/index.js
frontend/components/LoginForm/LoginForm.tsx
frontend/components/SignupForm/SignupForm.tsx
frontend/pages/dashboard/new-post.tsx
package-lock.json
package.json

**Issue:** #76 
This PR sets up and creates our first Integration tests for Cypress.
- Adds Cypress to the root of our project so that it can run integration tests on the entire app and later run the app.
- Sets up basic test organization closely following the exact recommendations from the Cypress founder.
- Adds a custom command for login while also providing a best practice pattern to strive towards but needs more investigation due to GraphQL.
- Adds first integration tests
**NOTE:** *The intent of this PR is to keep it fairly light and just get Cypress set up for Integration Tests, introduce general organization, provide some patterns and tests as references, while also writing our first tests. However, the intent isn't for the tests to be 100% perfect and fully-fledged just yet. I …

Add First Journaly Cypress Integration Tests

---

frontend/components/Dashboard/Post/Post.tsx
frontend/components/InlineFeedbackPopover/index.tsx
frontend/package-lock.json
frontend/package.json
frontend/utils/index.ts

This PR simply cherry picks [this commit](https://github.com/Journaly/journaly/pull/98/commits/b951961739050aa8ec9e86fe0292df15edb89b86) from #98 so that we can start using the `xss` library in `master`. 
No visual changes

Use isomorphic library for sanitizing

---

backend/src/graphql.ts
backend/src/utils.ts
frontend/components/Dashboard/Post/Post.tsx
frontend/components/JournalyEditor/JournalyEditor.tsx
frontend/components/PostBodyStyles/PostBodyStyles.tsx
frontend/components/PostBodyStyles/index.tsx

BE will now serialize bold, italic, and underlined editor content instead of silently ignoring it.
Also combined some styling for post editor/post pages most notably making block quotes format correctly on post pages.

Better editor saving support

---

frontend/components/Dashboard/PostCard/PostCard.tsx
frontend/components/PostBodyStyles/index.tsx

Fixes build errors for deployment.

Fix Build Errors

---

frontend/components/Dashboard/Nav/Nav.tsx
frontend/components/Dashboard/Nav/NavLinks.tsx
frontend/components/Layouts/DashboardLayout.tsx

**Issue:** Closes #144 
This fixes the nav from jumping around on each page load and also centers the links vertically on the page. It also updates the nav background and hover color

Fix bugs with the side nav

---

frontend/components/Dashboard/Nav/Nav.tsx
frontend/components/JournalyEditor/JournalyEditor.tsx
frontend/components/Layouts/DashboardLayout.tsx
frontend/components/Layouts/SettingsPageLayout.tsx
frontend/pages/dashboard/my-feed.tsx
frontend/pages/dashboard/my-posts.tsx
frontend/pages/dashboard/new-post.tsx
frontend/pages/dashboard/profile.tsx

**Issue:** Closes #150 
Fixes issue described in #150 as well as the mismatch of classNames between server and client. 
width="400" />
🚨 Note: position of J is fixed in #147 🚨 
width="400" />

Dynamically get currentUser from inside <Nav />

---

frontend/elements/TabToggle/TabToggle.tsx
frontend/pages/dashboard/my-posts.tsx

**Issue:** Closes #133 
This PR adds a slide animation for the `TabToggle`.

Add slide animation to TabToggle

---

frontend/components/Dashboard/Post/Post.tsx

**Issue:** closes #157 
Fixes a couple of visual bugs with the Post:
- background should be white
- image/header should be full-width
1. Go to the "✅ Preview" link from the Vervel build (🤩🤩🤩)
1. Log in and click on any post in your gawjus feed
1. See that the post background is white and the header image is now full-width and totally beauwtiful 🥰

Fix Post background color and header/image width

---

frontend/components/Dashboard/MyPosts/MyPosts.tsx
frontend/pages/dashboard/my-posts.tsx

**Issue:** #103 
Move the title above the toggle and update it to be `My Posts`.

Move title to above toggle

---

frontend/components/Dashboard/Settings/LanguagesForm.tsx
frontend/components/LanguageMultiSelect/LanguageMultiSelect.tsx
frontend/components/LanguageMultiSelect/index.tsx
frontend/components/LanguageSelect/index.tsx
frontend/elements/Button/Button.tsx
frontend/generated/graphql.tsx
frontend/graphql/addLanguageLearning.graphql
frontend/graphql/addLanguageNative.graphql
frontend/graphql/languages.graphql
frontend/graphql/languagesFormData.graphql
frontend/graphql/removeLanguageLearning.graphql
frontend/graphql/removeLanguageNative.graphql
frontend/nexus/graphql.ts
frontend/nexus/index.ts
frontend/nexus/language.ts
frontend/pages/api/graphql.ts
frontend/pages/dashboard/settings/profile.tsx
frontend/public/static/locales/en/common.json
frontend/public/static/locales/en/settings.json
frontend/theme/index.ts

Wires up languages section of the profile page allowing users to add/remove native/learning languages. Could probably use a little design touchup, but I'll leave that to someone who's good at these things.

Add language

---

frontend/components/Dashboard/Nav/NavLinks.tsx
frontend/components/Dashboard/Post/Post.tsx
frontend/components/InlineFeedbackPopover/index.tsx
frontend/generated/graphql.tsx
frontend/graphql/logout.graphql
frontend/nexus/user.ts

Also makes logout work because that had to be in place to test.

Hide thread/comment creation UI for non-logged-in users

---

frontend/components/Dashboard/Header/Header.tsx
frontend/components/Dashboard/Nav/Nav.tsx
frontend/theme/index.ts

**Issue:** closes #183 
Fixes the mismatch between the nav background color in mobile nav vs. side nav which wasn't updated when we darkened the nav color.
Also adds that color to the theme.

Fix Nav Color Mismatch

---

frontend/components/Dashboard/MyFeed/MyFeed.tsx
frontend/components/Dashboard/PostCard/PostCard.tsx
frontend/components/Icons/ChevronIcon.tsx
frontend/components/Pagination/Pagination.tsx
frontend/generated/graphql.tsx
frontend/graphql/feed.graphql
frontend/nexus/post.ts
frontend/pages/dashboard/my-feed.tsx

**Issue:** #107 
- Sets up pagination in the `My Feed` page
- Implements new design of drop downs
**NOTE:** This is to be made into reusable component in a follow-up PR
cc: @nlitwin

Set up My Feed pagination & improve drop down styling

---

frontend/components/PostBodyStyles/PostBodyStyles.tsx

Update sub-header styles in posts

---

frontend/components/Dashboard/MyFeed/MyFeed.tsx
frontend/components/Dashboard/PostCard/PostCard.tsx

**Issue:** Closes: #201 
Improving the grid 🔲 🔲 🔲 🔲  as described in the issue above

Improve the grid on the My Feed page

---

frontend/lib/mail.ts
frontend/nexus/graphql.ts

Tiny email copy fix

---

frontend/components/LanguageMultiSelect/LanguageMultiSelect.tsx
frontend/components/LanguageSelect/index.tsx
frontend/pages/post/[id]/index.tsx

**Issue:** Closes: #204 
Fixes the nav on the post page. By moving the `<DashboardLayout />` into the `<LoadingWrapper />`, it calculates the `currentUser` value before loading the nav.
This PR also updates the styles of the language selectors. See screenshots below

Fix nav on the Post page and update language selector styles

---

frontend/components/Dashboard/Post/Post.tsx
frontend/utils/date.ts

**Issue:** #212 
Adds the author name & date to the header of a post

Add more information to the Post header

---

frontend/components/Dashboard/MyFeed/MyFeed.tsx

Set max 3 columns of PostCards on the My Feed page

---

frontend/components/Dashboard/Post/Post.tsx
frontend/components/InlineFeedbackPopover/index.tsx

Revert "Fix for first selection emptying without reason, and closing of thread popovers"

---

frontend/components/Dashboard/Post/Post.tsx
frontend/components/InlineFeedbackPopover/Comment.tsx
frontend/components/InlineFeedbackPopover/index.tsx
frontend/generated/graphql.tsx
frontend/graphql/fragments.graphql
frontend/theme/index.ts

**Issue:** closes #113 
- Builds out the ability to `update` and `delete` actions for comments inside of threads.
- Breaks comments out into their own component
- Drastically improves commenting UI!
- Adds avatar to comments
- Makes use of our theme buttons
- Improves some minor layout/spacing things so that everything is consistent

Add update & delete comment functionality and improve comment thread UI

---

frontend/nexus/graphql.ts

Prevent Email Notifications About Your Own Comments

---

frontend/components/Dashboard/Settings/DetailsForm.tsx

Quick fix for form validation errors in the details form of the settings page. This PR is pointed into #239 so that it's easier to see the diff and not just commit directly to the PR.

Update details form validations

---

frontend/components/Dashboard/Post/Post.tsx
frontend/components/PostHeader/index.tsx

POSTS: GREATLY Improve Post styles for tablet & mobile

---

frontend/nexus/utils.ts

Exactly what it says in the title :)
Like other htmlification changes, only affects posts as they are stored, so existing posts will continue to have the problem unless they are edited and saved.

Correctly html-ify list items. Fixes #253

---

frontend/components/Dashboard/PostCard/PostCard.tsx
frontend/nexus/post.ts
frontend/nexus/utils.ts

**Issue:** Closes: #255 
This PR aligns the count query with the posts query on the My Feed page (drafts were omitted from the posts query, so the count query needs it too)

Fix number of pages for a given number of posts

---

.env.example
components/AuthGate/AuthGate.tsx
components/Dashboard/Profile/PostList.tsx
components/Dashboard/Profile/Profile.tsx
generated/graphql.tsx
graphql/profile.graphql
lib/apollo.tsx
nexus/post.ts
nexus/user.ts
pages/dashboard/profile/[id]/index.tsx

Order "Recent Posts" on profile page by publish date.

---

components/Dashboard/Post/Post.tsx

Fix position of new thread popovers and create thread button when scrolled

---

nexus/user.ts

**Issue:** fixes #297 
Currently, if a user attempts to log in with a capital letter in their email address, our system won't recognize their email address. This PR lowercases the email arg and DB value before updating it or checking it for login.

🐞 Email addresses should be lowercased on update & login

---

components/PostEditor/PostEditor.tsx
components/PostEditor/index.tsx
generated/graphql.tsx
graphql/post/editPost.graphql
hooks/useAutosavedState.ts
nexus/post.ts
pages/dashboard/new-post.tsx
pages/post/[id]/edit.tsx

Improves design of our `PostData` type and makes it so that we save and check a timestamp for each edit of a post, and discard the autosaved values if the last save it more recent.

Improve Autosaving Functionality

---

generated/graphql.tsx
graphql/profile/profile.graphql
lib/apollo.tsx
pages/dashboard/profile/[id]/index.tsx

Add Apollo dev hook

---

components/Dashboard/Settings/LanguagesForm.tsx
components/LanguageFormField/LanguageFormField.tsx
elements/MultiSelect/MultiSelect.tsx
elements/MultiSelect/OptionPills.tsx
elements/MultiSelect/index.ts
elements/Select/Select.tsx
generated/graphql.tsx
graphql/language/addLanguageRelation.graphql

Add language select w/ level (take 1)

---

components/Dashboard/MyFeed/MyFeed.tsx
components/Dashboard/PostCard/PostCard.tsx
components/LanguageFormField/LanguageFormField.tsx
generated/graphql.tsx
graphql/fragments.graphql

**Issue:** closes #352 
This is it. Beta, here we come. 🚀

The Final Alpha Branch: PostCard Fix & Language Level Select Visual Improvements

---

components/Dashboard/Post/Post.tsx
components/Dashboard/Post/PostAuthorCard.tsx
components/Dashboard/Profile/ProfileCard.tsx
components/Icons/FacebookIcon.tsx
components/Icons/GlobeIcon.tsx
components/Icons/InstagramIcon.tsx
components/Icons/YoutubeIcon.tsx
components/PostEditor/PostEditor.tsx
components/PostHeader/PostHeader.tsx
scripts/seed.ts

- Adds topics in the seed script, and updates language learning/native selection in seed script to use new language relations
- Scale social media icons on profile to work on very narrow screens
- Fixes issue where post editor would show an empty language badge
- Updates post header to show post language in editor when one is selected
- Updates post header to show topics in editor when one is selected
- Fixes missing `key` prop for user languages in post author card

Misc visual/seed fixes

---

components/Dashboard/Settings/UpdatePasswordForm.tsx
generated/graphql.tsx
graphql/user/updatePassword.graphql
nexus/user.ts
pages/dashboard/settings/account.tsx
public/static/locales/en/settings.json

**Issue:** closes #368 
Hi!
I added the update password functionality. Let me know if it's fine
...

Wire Up The Update Password Functionality In Settings

---

.circleci/config.yml

**Issue:** closes #375 
Sets up CircleCI

Set up CircleCI 

---

components/Dashboard/Post/Post.tsx
utils/index.ts

**Issue:**  Fixes #387 
Note: only tested in simulator. Can reopen if this persists on real devices
FE only
See issue

iOS copy/paste "context menu" obscures create thread button

---

nexus/user.ts

Not in the closed beta period anymore, so we don't need to create users with this badge

Stop handing out beta badge.

---

j-mail/serverless.yml
j-mail/src/emails/updateEmail.ts
j-mail/test-email.html

Changes update cron schedule to be once daily (it was already deployed like this, but I never committed the change), and fixes the issue where gmail shows the update email as a set of columns.

Some last minute changes to j-mail

---

nexus/user.ts

Super small one, just what it says on the tin.

Only include published posts in `postsWrittenCount`.

---

components/Dashboard/Post/PostAuthorCard.tsx
public/static/locales/de/authentication.json
public/static/locales/de/comment.json
public/static/locales/de/common.json
public/static/locales/de/my-feed.json
public/static/locales/de/my-posts.json
public/static/locales/de/post-author-card.json
public/static/locales/de/post.json
public/static/locales/de/profile.json
public/static/locales/de/settings.json
public/static/locales/en/post-author-card.json

**Issue:** closes #454 
Adds all German UI translations!
No migs

Add German UI Translations

---

components/Dashboard/PostCard/PostCard.tsx

**Issue:** #468 
Simple fix for making sure images display the same height in `PostCard`s.
Credit to @Lanny 🙌🏼
No migs

Make PostCard images same height

---

components/Dashboard/Post/PostComments.tsx
generated/graphql.tsx
graphql/comment/createPostComment.graphql
pages/post/[id]/index.tsx
utils/number.ts

**Issue:** closes #476 
https://www.loom.com/share/b997dd620fe647d3b6b01a7e3cf263ff

feat: optimistic-ui create post comment

---

hooks/useImageUpload.ts
public/static/locales/en/common.json

**Issue:** #482
Catch exceptions when doing XHR, hopefully will make whatever issue people are running into with #482 more apparent and at least won't get them stuck in an infinite spinner state.

More robust error handling in image uploading.

---

components/Dashboard/Nav/Nav.tsx
components/Icons/HelpIcon.tsx
public/static/locales/en/common.json

**Issue:** closes #483 
A very simple solution for providing a way for users to get help or report bugs directly inside the UI.
Uses our `<Modal>` component to simply display some instructions to the user.
No miggity migs.

Build simple help button

---

components/Dashboard/Nav/Nav.tsx
components/InlineFeedbackPopover/Thread.tsx
components/JournalyEditor/helpers.ts
components/Pagination/Pagination.tsx
components/PostEditor/PostEditor.tsx
public/static/locales/de/common.json
public/static/locales/de/my-feed.json
public/static/locales/de/post.json
public/static/locales/de/settings.json
public/static/locales/en/common.json
public/static/locales/en/my-feed.json
public/static/locales/en/post.json

One last round of translation gaps hopefully! 🤞🏼 I've updated [the spreadsheet](https://docs.google.com/spreadsheets/d/1NkyPTvK4DCDtbSyMfhIj3pI8obhbC_CzHZJbyP19uEE/edit?usp=sharing) accordingly as well so everything should be ready for new language translations 💪🏼
No migs ✌🏼

Fill in last UI translation gaps!

---

README.md
packages/README.md
packages/j-db-client/README.md
packages/j-mail/README.md

Following our big project re-org in #497 , this PR is to clean up, update, and improve our documentation 🎉
Nada
Marvel at those beautiful READMEs

Update project documentation - Feb 2021

---

packages/web/components/Dashboard/Nav/Nav.tsx
packages/web/components/Dashboard/Post/Post.tsx
packages/web/components/GoogleAnalytics/GoogleAnalytics.tsx
packages/web/components/GoogleAnalytics/index.tsx
packages/web/components/InlineFeedbackPopover/index.tsx
packages/web/components/LoginForm/LoginForm.tsx
packages/web/generated/graphql.tsx
packages/web/graphql/post/editPost.graphql
packages/web/hooks/useAuthCheck.ts
packages/web/lib/apollo.tsx
packages/web/package-lock.json
packages/web/package.json
packages/web/pages/_app.tsx
packages/web/pages/post/[id]/edit.tsx
packages/web/styles/globalStyles.css

Includes #522 so that has to get merged first.
Addresses #523 and #519

Misc fixes

---

packages/web/components/Dashboard/Post/Post.tsx
packages/web/components/Dashboard/Post/PostComment.tsx
packages/web/components/InlineFeedbackPopover/Comment.tsx

**Issue:** #513 
Also fixes issue where newlines in post comments and thread comments are not rendered, which I don't think we have a ticket for.

More misc fixes

---

packages/web/components/Dashboard/Post/Post.tsx

Remove margin between paragraphs

---

packages/web/components/Button/Button.tsx
packages/web/components/Dashboard/Post/Post.tsx
packages/web/components/Dashboard/Post/PostComment.tsx
packages/web/components/Dashboard/Post/PostComments.tsx
packages/web/components/InlineFeedbackPopover/Comment.tsx
packages/web/components/InlineFeedbackPopover/Thread.tsx
packages/web/components/Modals/ConfirmationModal/index.ts
packages/web/components/Modals/ConfirmationModal/useConfirmationModal.tsx
packages/web/components/Textarea/Textarea.tsx
packages/web/components/Textarea/index.ts
packages/web/public/static/locales/en/comment.json

Fixes #441
Also add simple shortcut ctrl+enter to submit comments when typing int comment textarea

Confirm when deleting comments

---

packages/web/components/Dashboard/Post/Post.tsx
packages/web/utils/dom.ts
packages/web/utils/index.ts

Mobile popover closing

---

packages/j-mail/package-lock.json
packages/j-mail/package.json

Fixes #561
Already deployed, this just brings the code up to date with what's in stage/prod.

Upgrade j mail db client

---

packages/web/resolvers/topic.ts

Restore optional chain that shouldn't have been deleted.

---

README.md
packages/web/nexus/subscription.ts
packages/web/nexus/utils/db.ts
packages/web/nexus/utils/index.ts
packages/web/nexus/utils/stripe.ts
packages/web/package.json
packages/web/scripts/grant-free-subscription.ts

Lets us give people zero cost subscriptions.

Added quickly hacked together `grant-free-subscription` script

---

packages/web/components/JournalyEditor/JournalyEditor.tsx
packages/web/components/JournalyEditor/Toolbar/Toolbar.tsx

**Issue:** No issue. Living on the edge man.
• Fixes missing padding in the Journaly Editor textarea
• Removes placeholder in the editor to fix IME bug
No migs

Minor visual fixes & updates to Journaly Editor

---

packages/web/resolvers/post.ts

URGENT HOT FIX - HeadlineImage Creation

---

packages/web/pages/post/[id]/edit.tsx
packages/web/resolvers/post.ts

URGENT HOT FIX P2 - Edit posts without new image

---

packages/web/resolvers/post.ts

URGENT HOT FIX P3: Post Deletion

---

packages/j-mail/src/emails/updateEmail.ts
packages/j-mail/src/handler.ts
packages/j-mail/src/utils.ts
packages/web/components/Dashboard/Post/Post.tsx
packages/web/generated/graphql.tsx
packages/web/graphql/post/updatePost.graphql
packages/web/pages/post/[id]/edit.tsx
packages/web/resolvers/post.ts

Revert "Fix editing post image."

---

packages/web/resolvers/post.ts

**Issue:** <#issue>
...
Journaly.com profile url (include if you'd like the "code contributor" badge):
If your PR doesn't involve any changes to the database, you can delete this section. If it does, briefly describe how it needs to be applied. Some common things you might mention are:
- Does the migration need to be applied before or after deploying code?
- Is applying the migration going to necessitate downtime?
- Is there any SQL or backfill logic that has to be run manually?
- Are the DB changes high risk in your estimation? Should a manual DB snapshot be taken before applying?

Quick bumpedAt Fix

---

packages/web/components/Dashboard/Post/PostComment.tsx

Fix bug where comment text disappears when editing multiple times

---

packages/web/components/Dashboard/Post/PostComment.tsx
packages/web/components/InlineFeedbackPopover/Comment.tsx
packages/web/next-env.d.ts
packages/web/package-lock.json
packages/web/package.json
packages/web/public/static/locales/en/comment.json

Revert "Markdown support for post & inline comments"

---

packages/web/components/Dashboard/Post/PostComment.tsx
packages/web/components/InlineFeedbackPopover/Comment.tsx
packages/web/package-lock.json
packages/web/package.json
packages/web/public/static/locales/en/comment.json

Add Markdown support for comments - Take 2, Part 2

---

packages/web/components/Dashboard/Post/PostComment.tsx
packages/web/components/InlineFeedbackPopover/Comment.tsx

I just realized that the original PR did not add support for inline comments. Pushing this through as I already announced the feature.

Add MD support for all comments

---

.dockerignore
Dockerfile
docker-compose.yml

Adds container support for both the postgres database and the web server.
**Issue:** <#568>
...
https://journaly.com/dashboard/profile/3068

Added initial docker files.

---

packages/web/components/Dashboard/Post/PostComment.tsx

Now that I see people using the newly supported checkboxes, I couldn't un-see those darn bullet points that were appearing next to them 😅

One last Markdown improvement - Checklist Styles

---

packages/web/components/Dashboard/Post/PostComment.tsx
packages/web/components/InlineFeedbackPopover/Comment.tsx

Just a few very minor last style improvements for our recent Markdown support.
- Remove bullet points from checkboxes in feedback comments
- Improve spacing for all checkboxes

Small Markdown Style Improvements

---

docs/approach-docs/in-app-notifications.md
docs/approach-docs/template.md

**Issue:**  #380 
In approach document for building an in-app notification system.

Approach Doc: In-App Notifications

---

packages/web/components/NotificationFeed/Notifications.tsx

A couple of small things to improve upon the initial release of In-App Notifications!

In-App Notifications Fast Follow-Ups - Part 1

---

packages/web/public/static/locales/de/settings.json

Updates to German translations for Settings page.

Update German translations settings.json

---

packages/web/public/static/locales/de/common.json

Updates to German translations for Settings page.

Update German translations in common.json

---

packages/web/public/static/locales/de/post.json

Updates to German translations for Settings page.

Update German translations in post.json

---

packages/web/resolvers/utils/index.ts

**Issue:** Closes #578
Previously this would result in a thread with equal start and end indices.
- [N/A] 🚨 Publish new j-db-client version and update in both `web` and `j-mail`
- [N/A] 🚨 Deploy migs to stage
- [N/A] 🚨 DEPLOY `j-mail` to stage
- [N/A] 🚨 Deploy migs to prod
- [N/A] 🚨 DEPLOY `j-mail` TO PROD
No migs, but to retroactively fix threads stuck in this zero-length limbo, we can run this query:
```sql
UPDATE "Thread" SET "archived" = TRUE WHERE "startIndex" = "endIndex";
```

Mark a thread as archived if a delete perfectly spans it 

---

packages/web/resolvers/post.ts

**Issue:** Closes #718
No migs required

Fix operator precedence in janky manual SQL compilation in posts resolver

---

packages/web/components/Dashboard/Settings/SettingsNav.tsx
packages/web/pages/dashboard/settings/tutorials.tsx
packages/web/public/static/locales/en/settings.json
packages/web/public/static/locales/en/tutorials.json

**Issue:**
- closes #678 
Builds a new "Tutorials" page that gives Journalers a place they can always go to learn everything they could want to know about how to use Journaly to the fullest ✨
No los hay
Coming soon!

🎓 Create Journaly Tutorials

---

packages/web/components/NotificationFeed/Notifications.tsx
packages/web/resolvers/utils/email.ts

Just a couple of last areas where URLs need to be updated to the new pattern correctly.

Small Improvements With New Profile URL Pattern

---

packages/web/components/GenericErrorBoundary/GenericErrorBoundary.tsx
packages/web/components/GenericErrorBoundary/index.ts
packages/web/components/NotificationFeed/NotificationFeed.tsx
packages/web/components/NotificationFeed/Notifications.tsx

No migs, just a bandaid to make wonk'd notifications not cause the whole page to crash

Make wonky notification data not cause the universe to implode.

---

packages/jadmin/jadmin.js
packages/jadmin/package-lock.json
packages/jadmin/package.json

**Issue:**
- closes #820 
* Creates a new package called Jadmin - Journaly Admin - to house scripts that handle admin-related tasks.
* Adds an interactive script that can handle deleting Users & Posts, with their related records, and can be extended in the future for other actions.
No migs 🍃
N/A

User post deletion script

---

packages/web/package-lock.json
packages/web/package.json
packages/web/pages/api/graphql.ts
packages/web/pages/api/stripe/webhook.ts
packages/web/resolvers/utils/request.ts

**Issue:**
- closes #4230
N/A
N/A

Log long running query bodies.

---

packages/web/components/Dashboard/MyFeed/MyFeed.tsx

**Issue:** #825
Resolves #825... kinda. 825 is resolved by config change and doesn't require code, but this PR adds some additional tracking and will trigger a build that will update the deployed config.
- [N/A] 🚨 Publish new j-db-client version and update in both `web` and `j-mail`
- [N/A] 🚨 Deploy migs to stage
- [N/A] 🚨 Deploy code to stage
- [N/A] 🚨 DEPLOY `j-mail` to stage
- [N/A] 🚨 Deploy migs to prod
- [N/A] 🚨 DEPLOY `j-mail` TO PROD
No migrations

Track changes to filters on my feed via custom GA event.

---

packages/web/config/i18n.js
packages/web/pages/settings/subscription.tsx

**Issue:**
* closes #858 
N/A
N/A

🐞 Quick Fix for broken translations on Feature Modal & Pricing Page

---

packages/web/components/Modal/Modal.tsx
packages/web/components/Modal/ModalBody.tsx
packages/web/components/Modal/ModalHeader.tsx
packages/web/components/Modal/modalConstants.ts
packages/web/components/UserList/UserList.tsx

**Issue:**
* Closes #830 
* Much needed visual bug fix for the User List modal, but also updated to ensure consistency across all modals.
* Removed `modalBreakpoint` constant and references for better consistency and replaced its usages with `Breakpoints.XS`.
No hay
**Before:**
**After:**

🔧 Fix Modal Visual Bug

---

packages/jadmin/jadmin.js

Adds a Jadmin script for assigning badges to users!
No miggies ☺️
N/A

Create Script For Awarding A Badge To A User

---

packages/web/components/Dashboard/Post/Post.tsx
packages/web/components/Dashboard/Post/PostComments.tsx
packages/web/components/InlineFeedbackPopover/Comment.tsx
packages/web/components/InlineFeedbackPopover/Thread.tsx
packages/web/pages/post/[id]/index.tsx
packages/web/pages/post/private/[id]/index.tsx

Quick fix - see code for details!

🐞 Suggestions: Fix bug with the logic for showing "Apply Suggestion" Button

---

packages/web/components/Dashboard/Post/Post.tsx

**Issue:**
* fixes #831 
Fixes post deletion bug. The issue was occurring during cache modification.

🥍🐞 Fix Post Deletion Bug 💥
