Journaly/journaly

- backend/package-lock.json
- backend/package.json
The `nexus-future` package now ships with `prisma2` which greatly reduces our overhead and need to manage this rapidly changing dependency ourselves 🙌🏼 So I'm removing this from our `devDependencies` and moving to the version that ships with `nexus-future`.
Upgrade packages:
```
"nexus-future": "^0.12.0",
"nexus-plugin-prisma": "^0.5.1"
```
> Upgrade `nexus-future` & move to relying on them for managing Prisma2 dependency

- backend/package-lock.json
- backend/package.json
- backend/prisma/schema.prisma
- backend/src/app.ts
- backend/src/graphql.ts
- frontend/components/Dashboard/MyFeed/MyFeed.tsx
- frontend/components/Dashboard/Post/Post.tsx
- frontend/graphql/createUser.graphql
- frontend/graphql/currentUser.graphql
- frontend/graphql/feed.graphql
- frontend/graphql/users.graphql
**Issue:** #49 
Both the `nexus-future` > now `Nexus` framework and `Prisma2` > now just `Prisma` 🥳 have had significant updates. Journaly's backend needs to be updated to support those updates.
Throwing in the initial casing updates, too.
> Upgrade Nexus & Prisma

- frontend/components/Dashboard/Dashboard.tsx
- frontend/components/Dashboard/Header/Header.tsx
- frontend/components/Dashboard/Header/index.ts
- frontend/components/Dashboard/Nav/Nav.tsx
- frontend/components/Dashboard/Nav/NavLinks.tsx
- frontend/components/Dashboard/Nav/index.ts
- frontend/components/Dashboard/Nav/nav-constants.ts
- frontend/components/Hooks/useWindowSize.ts
- frontend/components/Layouts/DashboardLayout.js
- frontend/components/Layouts/DashboardLayout.tsx
- frontend/pages/_document.tsx
- frontend/public/static/locales/en/common.json
- frontend/styles/globalStyles.css
- frontend/utils/breakpoints.js
- frontend/utils/colors.js
Resolves #35. This PR finishes styling the nav and adds transitions. See sub tasks for details. Follow up task for collapsing/expanding the nav manually in issue #57.
> Implement nav with transitions

- frontend/.prettierrc.js
- frontend/components/Hooks/useFocusTrap.ts
- frontend/components/Icons/XIcon.tsx
- frontend/components/Modal/Modal.tsx
- frontend/components/Modal/ModalBody.tsx
- frontend/components/Modal/ModalFooter.tsx
- frontend/components/Modal/ModalHeader.tsx
- frontend/components/Modal/index.ts
- frontend/components/Modal/modalConstants.ts
- frontend/elements/Button/Button.tsx
- frontend/elements/Button/index.ts
- frontend/pages/_document.tsx
- frontend/styles/globalStyles.css
- frontend/utils/css.ts
- frontend/utils/index.js
Resolves: #59 
Fully accessible modal, full screen on mobile, centered on desktop. See gifs below for UX
```jsx
const Component = () => {
const [openModal, setOpenModal] = useState(false)
const triggerElementId = 'open-modal-button'
const handleClick = () => setOpenModal(true)
return (
<Button id={triggerElementId} onClick={handleClick}>
Open Modal
</Button>
{openModal && (
<Modal
onClose={() => setOpenModal(false)}
title="This is the modal title"
body={<div>Content of the modal</div>}
footer={<div><button>Submit modal form</button></div>}
triggerElementId={triggerElementId}
maxHeight={'700px'}
/>
)}
```
> Create a modal component

- frontend/components/Dashboard/Header/Header.tsx
- frontend/components/Form/Form.tsx
- frontend/theme/index.ts
- frontend/utils/index.js
- frontend/utils/index.ts
POC for proposal #68 
🚨 Note: current typography font values are placeholders. They are not currently updated with our values
> Implement theme with typography, colors, and breakpoints

- backend/prisma/schema.prisma
- frontend/components/Dashboard/Post/Post.tsx
**Issue:** #88 
Handle loading a post with existing comments and being able to reconstruct the post with all highlights and comment threads in the exact position they were left in with the same text selection.
- We built this in a way that allows us to perfectly position persisted/exisitng comments and their text selections upon visiting a post, while not breaking that positioning when adding new comments.
- We achieved this by anchoring comment thread locations to the beginning of the document as a single source of truth.
- Some refactoring of re-used logic into functions and better function/variable names
- Added documentation/comments
> FEATURE: Inline Feedback Experience PART 2 - Handle Loading Persisted Comments

- backend/src/graphql.ts
- frontend/components/Dashboard/Post/Post.tsx
- frontend/components/InlineFeedbackPopover/index.tsx
- frontend/generated/graphql.tsx
- frontend/graphql/createThread.graphql
- frontend/graphql/fragments.graphql
- frontend/graphql/postById.graphql
Allow users to create new threads that are actually persisted to the DB.
Also created query fragments for queries/mutations so we get a consistent type/fieldset when querying.
*caveat*: Thread creation happens independently of creating the first comment on that thread, so you can highlight something and make a thread out of the highlight, but bail out of creating the comment so you get an empty thread. This seemed acceptable to me since you can come back and create a comment later and nothing in the UI is particularly wrong in this scenario, but wanted to call it out. Backing out a local highlight that's not yet committed to the DB is a little trickier if we want to mandate that threads have a single comment, but not too hard if we wanted to do that later.
> Allow users to create new threads that are actually persisted to the DB

- backend/src/graphql.ts
I got some helpful feedback from the Nexus core team that there's no need to declare all these `const`s in our GQL schema which makes perfect sense, so this is just to make some small improvements there 🙂
...
> Light refactoring of our Nexus GraphQL schema

- frontend/components/JournalyEditor/JournalyEditor.tsx
- frontend/components/JournalyEditor/Toolbar.tsx
**Issue:** closes #82 
Adds some very simple styles that are missing in the Journaly Editor. These can be improved later to be really unique and splendid aligned with the Journaly brand and style -- I already have some nice design ideas. Most important thing right now is to have something simple and nice.
Removes the "code" formatting button. This has been discussed in the past as something we won't support as we want to keep the editor as clean and simple as possible.
Also fixes one build error that I was going to fix separately but it is in the same file (unused `useState` import)
> Add Missing Styles For Journaly Editor

- frontend/components/Dashboard/Post/Post.tsx
- frontend/hooks/useAutosavedState.ts
- frontend/lib/apollo.tsx
- frontend/pages/dashboard/new-post.tsx
Title says it all.
Do we want any kind of visual indication that a post is saved locally? It wouldn't be too hard to add a little piece of copy that says like "unsaved changes" or "saved locally" or something. I didn't add it because my thought was that you don't really care about the feature until you fat finger something and think you've lost your post, at which point you'll discovery it was saved on going back, but if you think it will make folks more comfortable to have feedback on it right away we can throw that in.
> Autosave editor content on new post page.

- README.md
- backend/.env.example
- backend/prisma/.env.example
- backend/src/app.ts
- backend/src/graphql.ts
- backend/src/utils.ts
- frontend/codegen.yml
- frontend/generated/graphql.tsx
- frontend/graphql/feed.graphql
- frontend/graphql/fragments.graphql
- frontend/graphql/posts.graphql
**Issue:** #78 
This PR supports querying for posts by `authorId` and `status` (published / draft) on the frontend. All code comes directly from preexisting, closed PRs (#98, #134) in an effort to create smaller, more manageable PRs.
No visual changes
> Support querying posts by userId, status; expose excerpt, readTime

- backend/seed.ts
- backend/src/utils.ts
BE build should now work without TSC getting angry.
Also fixed issue with threads in seed data. Looks like commit a369380d610c4858b90df37e410b58fa0a6dc904 which removed the h1s from the post bodies threw off the indices  for the threads. At some point we should probably handle invalid selection ranges (e.g. which cross `<p>` tags, in these two cases) more gracefully. We do prevent these selections from happening in the UI, but they can still be created through request tampering and will cause the wonky rendering of posts seen here.
> More BE build fixes

- frontend/components/Dashboard/MyPosts/MyPosts.tsx
- frontend/components/Dashboard/MyPosts/index.ts
- frontend/components/Dashboard/PostCard/PostCard.tsx
- frontend/pages/dashboard/my-posts.tsx
🚨 Note: this PR originally came from #134 . The PR it pointed to needed to be broken up into smaller PRs, so now this one points to a different base branch (#139 ). Here is the original description:
**Issue:** Closes #103 
Now that we have a TabToggle on the My Posts page, we can add published and draft posts
> Display published and draft posts on the My Posts page

- frontend/components/Dashboard/MyFeed/MyFeed.tsx
- frontend/components/Dashboard/MyPosts/MyPosts.tsx
- frontend/components/Dashboard/PostCard/PostCard.tsx
🚨 Note: this PR originally came from #135 . The PR it pointed to needed to be broken up into smaller PRs, so now this one points to a different base branch (#140). Here is the original description:
**Issue:** #79 
This PR adds support for displaying avatars in the `<PostCard />` component. It also adds a `stacked` prop, which keeps the card in the stacked arrangement (image on top of post details), even on large screens.
🚨 Note: [this comment](https://github.com/Journaly/journaly/pull/135#pullrequestreview-442573798) has been addressed and now the post cards look like this:
> Update PostCards for use on the My Feed Page

- frontend/package-lock.json
- frontend/package.json
- frontend/pages/_app.tsx
- frontend/pages/_document.tsx
**Issue:** #146
Adding back the nprogress bar that we used to have 🕺🏻
> Add nprogress bar for page loads

- frontend/elements/ExternalLink/ExternalLink.tsx
`<a>`'s `href` prop doesn't seem to accept `URL`s, so cast to string here
Error:
```
Failed to compile.
/Users/ryanjenkins/journaly/frontend/elements/ExternalLink/ExternalLink.tsx
ERROR in /Users/ryanjenkins/journaly/frontend/elements/ExternalLink/ExternalLink.tsx(22,8):
22:8 Type '{ children: ReactNode; href: string | URL; target: string; rel: string; className: string; "aria-label": string | undefined; }' is not assignable to type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.
Type '{ children: ReactNode; href: string | URL; target: string; rel: string; className: string; "aria-label": string | undefined; }' is not assignable to type 'AnchorHTMLAttributes<HTMLAnchorElement>'.
Types of property 'href' are incompatible.
Type 'string | URL' is not …
```
> Handle URL typed `href` prop to `ExternalLink`

- frontend/elements/ExternalLink/ExternalLink.tsx
- frontend/pages/blog/introducing-journaly.tsx
- frontend/styles/globalStyles.css
**Issue:** Closes #148 
Fixed all issues mentioned in #148 and use the `ExternalLink` component on the blog
No visual changes since the `ExternalLink` component hadn't been used on text yet, only images
> Update the ExternalLink component

- frontend/components/Dashboard/Nav/Nav.tsx
This is a quick fix for positioning the Journaly logo in the side nav when users are not logged in
> Fix logo position for non-logged in users

- frontend/README.md
- frontend/components/Modal/Modal.tsx
- frontend/docs/4-e2e-tests.md
**Issue:** #76 
Adding some docs for Cypress so that anyone coming to the repo can quickly get a grasp of the framework and its philosophy. Down the line when we create custom commands and Journaly-specific infrastructure, we can add that to the docs as well!
> Add docs for Cypress

- frontend/components/Dashboard/Header/HamburgerIcon.tsx
- frontend/components/Dashboard/Header/Header.tsx
- frontend/components/Dashboard/Nav/Nav.tsx
- frontend/components/Dashboard/Nav/NavLinks.tsx
- frontend/components/Dashboard/Profile/PostList.tsx
- frontend/components/Dashboard/dashboardConstants.ts
- frontend/components/Layouts/DashboardLayout.tsx
- frontend/components/Layouts/SettingsPageLayout.tsx
**Issue:** #161 
This PR makes sure that no matter what the screen height or width, the user can view page content and scroll if necessary.
> Make dashboard, nav, and scrolled content responsive and visible

- frontend/components/Dashboard/MyPosts/MyPosts.tsx
- frontend/components/Dashboard/Profile/PostList.tsx
- frontend/components/Icons/LoadingSpinner.tsx
- frontend/components/LoadingWrapper/LoadingWrapper.tsx
**Issue:** #164 
Replace the loading text with a loading spinner while AuthGate is loading
> Add loading spinner to AuthGate

- frontend/components/Dashboard/MyFeed/MyFeed.tsx
- frontend/components/Pagination/Pagination.tsx
- frontend/components/Pagination/index.ts
**Issue:** #107 
Add the `Pagination` component and start wiring it up to the My Feed page. Eventually we'll want to get the `total` number of posts from the `useFeedQuery`, but for now, I'm just using `posts.length` for the total. The URL with the page query param looks like `http://localhost:3000/dashboard/my-feed?page=2`. I wasn't sure what to set for the number of posts per page on the My Feed page, so I set it to display 10 per page right now. I also kept the default number of items per page as it was from the Pagination component in the previous repo, which can be overridden by the parent if needed. Happy to change these default values if needed!
> Add pagination component

- frontend/components/Dashboard/Nav/NavLinks.tsx
- frontend/components/Layouts/DashboardLayout.tsx
**Issue:** #144 
Fixes the regression with nav transitions
> Fix nav transitions 🥳

- frontend/components/Dashboard/Post/Post.tsx
- frontend/generated/graphql.tsx
- frontend/graphql/editPost.graphql
- frontend/graphql/updatePost.graphql
- frontend/nexus/post.ts
- frontend/pages/dashboard/new-post.tsx
- frontend/pages/post/[id]/edit.tsx
- frontend/pages/post/[id]/index.tsx
- frontend/public/static/locales/en/post.json
closes #174 
Post authors can now edit their drafts. Chose not to give this functionality on published posts as we don't have a solid plan for managing comments/threads across edits
Also made titles on edit pages auto-save in the same way as post bodies, and moved "publish draft" button to the right place.
> Add edit post functionality

- frontend/components/Dashboard/Profile/PostList.tsx
- frontend/components/Dashboard/Profile/Profile.tsx
- frontend/components/Dashboard/Profile/ProfileCard.tsx
**Issue:** closes #178 
Fixes visual bugs on the profile page:
- Profile should have white background on the right side behind posts
- There should be a box shadow on this profile section
- The height of the profile is not right and gets messed up when the browser is slightly tall. Happens even on laptop but gets really bad on a larger screen
NOTE: Upon testing, there is a minor visual issue even after this PR where the social media icons get messed up if someone makes the window very short but still not mobile breakpoint, but this should be a rare use case and there's no time to handle that for now.
**Before:**
**After:**
> Fix profile visual bugs

- frontend/components/PostBodyStyles/PostBodyStyles.tsx
**Issue:** #175 
When the design system/theme was implemented, many styles were not properly updated around the app. I tried to fix most of these in a few previous PRs but the 'T' (title/h2) button in the Journaly Editor still wasn't restored. This PR fixes that.
> Restore styling for h2 in Posts

- frontend/components/Modal/Modal.tsx
- frontend/components/Modal/ModalBody.tsx
- frontend/components/Modal/ModalHeader.tsx
- frontend/components/Modals/WelcomeModal.tsx
- frontend/components/Modals/WelcomeModal/WelcomeModal.tsx
- frontend/components/Modals/WelcomeModal/WelcomeModalBody.tsx
- frontend/components/Modals/WelcomeModal/index.ts
- frontend/pages/dashboard/my-feed.tsx
**Issue:** Closes #173 
This PR adds a welcome modal that appears when a user first lands on the My Feed page. It appears after 5 seconds of landing on the page for now, but we can update this value. The user is presented with text indicating how adding languages is useful and that they can add languages later or update them on the settings page. Right now, the welcome modal is using the languages form as is it is on the settings page.
In a follow-up PR, I'll be working on:
- moving the language fields / form into a reusable component so that we don't have to duplicate them
- updating the styles
- updating the profile page to use language information from the `currentUser`
> Add Welcome Modal to the My Feed page

- frontend/components/Site/Nav/Nav.tsx
Users are very likely to come to Journaly via `journaly.com` but currently it's very confusing as there's no clear path to get to the dashboard unless you know the exact url path to the dashboard. This PR allows for conditionally rendering a dashboard link in the site nav.
> Implement a way to get to the dashboard from landing page when logged in

- frontend/components/PostBodyStyles/PostBodyStyles.tsx
Something definitely looked off about the styling of the posts and being hard to differentiate the sub titles from the body text. I think this greatly improves it!
> Improve Post Sub Title Styles

- frontend/nexus/post.ts
Adds extra condition to `feed` query so that drafts do not show on My Feed page
...
> 🔥 FIRE: Drafts are showing in `My Feed` page and causing server errors and user concern/confusion

- frontend/components/Dashboard/PostCard/PostCard.tsx
- frontend/generated/graphql.tsx
- frontend/graphql/fragments.graphql
**Issue:** closes #211 
- A number of users have noted that it would be super helpful to have more information on the `PostCard`s in the feed:
- post language
- This PR adds a language badge underneath the author information on a `PostCard` only when it is in the feed
**NOTE:** There is also a great use case for displaying the language badge in the other scenarios (`!stacked` and on the profile, for example) but it requires restructuring the component quite a bit and after spending over 30 mins just messing with that, I decided this is WAY higher impact so best to merge this in as is and @nlitwin you could work on the other use cases since you're most familiar with that component. We can discuss the visual design.
> Add Language Badge to PostCards in My Feed 

- frontend/components/PostBodyStyles/PostBodyStyles.tsx
- frontend/nexus/utils.ts
Title is pretty much all there is to it, fixes the problem where empty paragraphs used for spacing out content get rendered in the editor but not on the post page. Only affects posts going forward, but editing a post and saving with no changes will retroactively apply this logic.
> Render empty paragraphs consistently between editor and post page.

- frontend/components/Dashboard/Profile/PostList.tsx
- frontend/components/Dashboard/Profile/Profile.tsx
**Issue:** Closes: #223 
Fixes this described in the issue above:
> Allow profile sections to take up more height

- frontend/components/LoginForm/LoginForm.tsx
- frontend/components/SignupForm/SignupForm.tsx
**Issue:** Closes: #207 
The animation for our login and signup form fieldset had an old `&` for SCSS syntax that was probably brought over from the previous repo. Replacing `&` with `fieldset` fixes the animation of the linear gradient in the forms and fixes the scoping of the animation, so that the animation doesn't apply to the LastPass Chrome extension icon.
> Fix fieldset ::before animation, which fixes LastPass animation

- frontend/nexus/post.ts
**Issue:** fixes #219 
Fixes the feed page so that it sorts posts by `createdAt: `DESC` / newest posts first.
> My Feed page should sort by newest posts first

- frontend/components/Dashboard/Post/Post.tsx
- frontend/components/InlineFeedbackPopover/index.tsx
Changes the way highlight and click-out detection is done to fix issues with empty selections and closing thread popovers.
fixes #221
> Fix for first selection emptying without reason, and closing of thread popovers

- frontend/components/Dashboard/Post/Post.tsx
- frontend/components/InlineFeedbackPopover/index.tsx
UI failed spectacularly when an empty thread (a thread that spans from e.g. 0 to 0) was present on a post. This traces back to a DB issue we need to fix, but this PR updates the UI to handle it more gracefully.
> Fix reverted stuff

- frontend/components/Dashboard/MyFeed/MyFeed.tsx
As suggested by some testers, since the ideal page layout is 3 posts per row (or 3 columns), it feels right to have 9 posts per page.
> Update My Feed to 9 posts per page

- frontend/pages/about.tsx
- frontend/pages/blog/introducing-journaly.tsx
**Issue:** `/about` and `blog/introducing-journaly` pages are currently broken due to throwing Apollo errors
Satisfies those errors for now.
> Fix broken `/about` and `/blog/introducing-journaly` pages

- frontend/pages/dashboard/index.tsx
Currently, `/dashboard` returns a 404. This PR aliases `/dashboard` to /`dashboard/my-feed`.
> Alias `/dashboard` to /`dashboard/my-feed`

- frontend/components/Dashboard/Post/Post.tsx
🔥 Author isn't displaying in `PostHeader` or page `<Head>` for users who don't have a `name` yet (all of them).
Uses `handle`
> 🔥 PROD FIX: Author not displaying on posts

- frontend/components/JournalyEditor/JournalyEditor.tsx
- frontend/pages/dashboard/new-post.tsx
- frontend/pages/post/[id]/edit.tsx
Clear selection before resetting editor content on new post page, preventing a crash on submit.
> Clear selection before resetting editor content on new post page

- frontend/components/Dashboard/MyFeed/MyFeed.tsx
We should stop console logging the current user in the browser on the my feed page. It will be simple to bring `currentUser` back when we start using it.
> Stop logging current user on Feed

- frontend/components/Dashboard/Post/Post.tsx
- frontend/components/Dashboard/PostCard/PostCard.tsx
- frontend/components/PostHeader/index.tsx
- frontend/pages/dashboard/new-post.tsx
**Issue:** #265 
Display right-to-left languages correctly on PostCards and the Post page
> Use dir="auto" to format RTL languages

- frontend/components/Dashboard/Post/Post.tsx
- frontend/components/InlineFeedbackPopover/Comment.tsx
- frontend/package-lock.json
- frontend/package.json
- frontend/pages/_app.tsx
- frontend/public/static/locales/en/post.json
- frontend/styles/react-toastify-overrides.css
**Issue:** Closes #251 
This PR introduces toast messages with the [react-toastify](https://github.com/fkhadra/react-toastify) library. It's lightweight and very customizable. I've only added the libary, basic style overrides for the "success" toast message, and one example. If we like it, I can add more overrides for other toast message variations, e.g. `info`, `error`, etc. and more usages of it throughout the app
> Add basic toast message and style overrides

- frontend/components/Dashboard/Post/Post.tsx
- frontend/components/Dashboard/PostCard/PostCard.tsx
- frontend/generated/graphql.tsx
- frontend/graphql/fragments.graphql
- frontend/nexus/post.ts
- frontend/pages/_app.tsx
Resolves #271 
Previously `PostCard`s displayed the thread count, I believe it seemed off because of the empty selection threads issue where there wouldn't be a visible thread on the post but they would exist in the DB. Now we use the count of comments on the post (still possible off if there is a comment in a empty selection thread) but it should be correct going forward as the empty selection thread issue shouldn't happen anymore.
Also addresses issue where the comment popover (near the bottom of a post, especially on short posts where the post container is less than half the vertical height of the screen) could be clipped off by the post container.
> Fix comment count on post cards and issue where comments would be clipped off by post container

- components/Dashboard/Post/Post.tsx
- components/Dashboard/Post/PostAuthorCard.tsx
- components/Dashboard/Post/PostComments.tsx
- components/InlineFeedbackPopover/Comment.tsx
- generated/graphql.tsx
- graphql/fragments.graphql
- pages/post/[id]/index.tsx
**Issue:** closes #277 
Currently, posts are quite bare and they feel quite detached from the author who wrote them. We need to make the posts feel a lot more personalized to the author and help readers feel more of a connection and sense of community!
This PR adds the beginnings of a nice author card to the post displaying information and with a link to their profile!
It also adds a placeholder for the post general comments (#278 ) which will be a follow-up ticket.
It also provides the first entry point for viewing another person's profile! 🙌🏼
Finally, with the above point in mind, I also made comment author avatars clickable as well which takes you to their profile 😄
More information will be added to the card this week and it will be made to look much nicer! 😍
> POSTS: Create Post Author Cards!

- pages/post/[id]/index.tsx
The new bottom section of the post page can expand wider than the post content. This is a quick hot fix as the feature was just released!
> Quick fix for max width on post section

- components/Dashboard/Nav/NavLinks.tsx
Fixes issue where logging out would leave you with the "dashboard" link on the main page until the next refresh.
> Clear currentUser cache on logout.

- styles/globalStyles.css
Fixes issue where FF (and maybe brave?) positioned popovers incorrectly. Gives `body` tag `position: relative` so popovers are positioned relative to it, rather than doc root, which apparent browsers size differently based on default UA stylesheets
> Fix some cross browser issues with popover positioning.

- components/Dashboard/PostCard/PostCard.tsx
Safari was shrinking flex items where other browsers were not. Adding `flex-shrink: 0` prevents this from happening
> Prevent PostCards from shrinking

- components/Dashboard/Profile/ProfileCard.tsx
- components/Dashboard/Settings/BioForm.tsx
- components/Dashboard/Settings/LanguagesForm.tsx
- components/Dashboard/Settings/SettingsForm.tsx
- generated/graphql.tsx
- graphql/fragments.graphql
- graphql/user/settingsFormData.graphql
- graphql/user/updateUser.graphql
- nexus/user.ts
- pages/dashboard/settings/profile.tsx
- public/static/locales/en/settings.json
**Issue:** Part of #172 
This PR allows a user to view and update their bio 🙌🏼 It also adds minor things like displaying the dialect of languages on the `ProfileCard` and a toast success message after updating the bio. When submitting the bio form, it updates so fast that it's easy to not see the loading state of the button, so the toast message should help with that. If that pattern looks good, we can add toast success messages for the rest of the settings page updates, since it's a similar situation of updating fast and not being 100% sure if it worked or not.
> View and update bio

- components/Dashboard/Post/PostComments.tsx
- components/InlineFeedbackPopover/index.tsx
**Issue:** Closes: #295, fixes: #262
> Move comment submit buttons below textarea

- components/Modals/WelcomeModal/WelcomeModal.tsx
- pages/dashboard/my-feed.tsx
**Issue:** Closes: #313 
Don't show the modal to existing users who have seen the welcome modal and already have native and learning languages set.
> Don't show modal on new devices/browsers if the user has languages set

- components/Dashboard/MyPosts/MyPosts.tsx
- components/Dashboard/Profile/PostList.tsx
- components/Dashboard/Profile/Profile.tsx
- components/TranslationLink/TranslationLink.tsx
- components/TranslationLink/index.ts
- docs/1-internationalization.md
- pages/dashboard/profile/[id]/index.tsx
- public/static/locales/en/my-posts.json
- public/static/locales/en/profile.json
**Issue:** Closes #315 
A few of our lists of posts don't have any empty state. This PR adds an empty state to the list of published posts and drafts on the My Posts page as well as the Recent posts section of the user profile. Additionally, the profile now is aware of whether the profile is being viewed by the logged in user or someone else. This can allow future features like CTA text on the ProfileCard, prompting the logged in user to add missing profile details.
> Add empty states to lists of posts

- nexus/language.ts
**Issue:** closes #317 
Currently the ordering of languages in the dropdowns is random and now we have a lot of languages in there.
This PR orders them alphabetically.
> Order languages alphabetically

- components/Dashboard/MyPosts/MyPosts.tsx
- components/Dashboard/PostCard/PostCard.tsx
**Issue:** Closes #310 
This PR also fixed `PostCard`s that appear very narrow on large width screens. See before and after screenshots below
> Ensure 2 columns of same size

- components/Dashboard/PostCard/PostCard.tsx
- elements/LineClamp/LineClamp.tsx
- elements/LineClamp/index.ts
**Issue:** Closes #322 
Exploratory PR to see if line clamping the `PostCard` title and excerpt looks good and is something that we want to do. Right now, the excerpts on each `PostCard` can be a different number of lines, so the `PostCard` content isn't able to line up nicely with the accompanying image.
🚨 Note: 🚨 we can have a custom number of lines clamped, for example on the My Feed page. See screenshots below labeled "Custom number of lines clamped"
- The My Feed page uses the `stacked` prop on the `PostCard`, which ensures that the `PostCard` always has the image on top and that the horizontal layout (image on the left, content on the right) is never shown. With the stacked prop, the `margin-top` between the post excerpt and the post stats is 24px. When not using the `stacked` prop, …
> LineClamp the PostCard title and excerpt

- pages/dashboard/profile/[id]/index.tsx
**Issue:** Closes: #321 
In #273, a new profile page was created that uses the id of the user in the URL. The old profile page was using `withPadding={false}` on the `<DashboardLayout />` because the profile page is full width on mobile and needs to override the default padding that's used on all the other pages and set by `DashboardLayout`. This PR simply puts back that removed prop.
> Put back removed withPadding={false}

- nexus/comment.ts
**Issue:** fixes #331 
Fixes the thread deletion bug so that for the time being we manually delete all associated `threadSubscription`s before deleting the thread itself.
> Fix Thread Deletion Bug

- components/Layouts/LandingPageLayout.tsx
**Issue:** closes #341 
- We've had quite a high % of alpha users report pain points around journaly.com not automatically taking them to their dashboard once they're signed up and logged in.
- I discussed this with Lindie and she made the point that once she's signed up and logged in, there's really no reason for her to go back to the landing page.
This PR automatically redirects logged in users to the dashboard.
**NOTE**:
We'll have to think about the blog but I think it's not too important for now.
> Redirect Logged In Users To Dashboard Automatically

- components/SignupForm/SignupForm.tsx
**Issue:** fixes #344 
Sign up is broken in production, reported to a new Patreon supporter who was trying to sign up today. This PR reverts the last changes we made to the regex validating the email input in the signup form.
> 🚨 Sign up broken: Revert changes to signup form regex

- components/InlineFeedbackPopover/Comment.tsx
**Issue:** #348 
I think it will really help to add another really nice extra touch of community sentiment by displaying how many people have shown thanks for a certain comment/piece of feedback 🙂
> Add number of thanks for each comment

- components/Dashboard/Post/Post.tsx
- components/Dashboard/Post/PostAuthorCard.tsx
- components/Dashboard/PostCard/PostCard.tsx
- components/Dashboard/Profile/PostList.tsx
- components/Dashboard/Profile/Profile.tsx
- components/Dashboard/Profile/ProfileCard.tsx
- components/Dashboard/Settings/DetailsForm.tsx
- components/Dashboard/Settings/InterestsForm.tsx
- components/Dashboard/Settings/SocialForm.tsx
- components/PostEditor/PostEditor.tsx
- components/PostHeader/PostHeader.tsx
- elements/LevelGauge/LevelGauge.tsx
- elements/LevelGauge/index.tsx
- elements/MultiSelect/MultiSelect.tsx
- generated/graphql.tsx
- graphql/fragments.graphql
- pages/dashboard/profile/[id]/index.tsx
- pages/dashboard/settings/account.tsx
- public/static/locales/en/post-author-card.json
- utils/languages.ts
**Issue:** #352 
Builds out UI things for our language level feature along with a couple of other UI improvements around topics.
> Language Levels - UI

- README.md
I don't seem to be able to add Notes to the Kanban, so I am unable to follow the normal workflow for this PR. I created an issue for this (after the PR) #364 but am unsure how to get it on the Kanban.
closes #364 
These are changes I needed to make to the `Readme.md` file in order to try and get Journaly running locally on my Windows machine.
1. I updated the section Postgres installation to include how one installs it on Windows.
1. I fixed what I believe as a typo, referencing the `backend` directory when it was supposed to be the `prisma` directory.
1. I made additions to where we have to make changes to `.env.example`, as there are two instances of that file. This may be incorrect, and it is working for me now, but I'm unsure if I have superfluous files at the moment (I am not …
> Add update some lines and add notes for Windows users

- components/Icons/FlagDEIcon.tsx
- components/Icons/FlagUSIcon.tsx
- components/UILanguageSelect/UILanguageSelect.tsx
- components/UILanguageSelect/index.ts
- config/i18n.js
- pages/dashboard/settings/profile.tsx
Fixes issue with users with a german browser setting not being able to edit posts. Does this by disabling locale subpaths functionality with next-i18next (dynamic routes and locale subpaths don't work together, apparently. I liked locale subpaths, so I'm sad to see them go, but if they don't work then they just don't work.
Also added a little widget to the profile page to let you change languages for testing purposes. Probably doesn't belong here long term, but it seemed alright for now.
> Remove locale subpaths

- components/Dashboard/MyFeed/MyFeed.tsx
- docs/contributing-guide.md
**Issue:** closes #346 
I don't mean to compet with @robin-macpherson's solution in #347 but it seems like that has been hanging for a while, and a lot of issues appear to be assigned but maybe on hold. So I grabbed what appeared to be something I could tackle
Essentially, my fix creates a new function to reset the pagination when the filters are edited. I use the [router.push()](https://nextjs.org/docs/api-reference/next/router#routerpush) method to adhere to single responsibility principles and ensuring that all intended "side effects" are taken care of (such as the url updating properly).
I would love someone to look this over and give me feedback. There are a few items in particular I was curious about (being new to the codebase) and would love some eyes on:
1. I am currently using a …
> call pagination reset from filters

- nexus/post.ts
**Issue:** closes #383 
I've been noticing that when you first look at the feed, it appears that a lot of posts don't have comments due to the 0 comment count shown on the PostCard, which gives a perception that a lot of posts don't have engagement.
However, once clicking into a bunch of them, I see there are post-level comments.
Since the main purpose of displaying that comment count on the post card is to indicate the level of post engagement, and we do want people to have a good impression that it is worth it to write posts, I think this might help achieve a more accurate perception.
**Left:** Updated count (shows 5), **Right:** Old count (shows 0)
**Here you can see that basically all counts are higher with this update including two that were 0 before**
> Include PostComments in commentCount on PostCards

- nexus/user.ts
**Issue:**
Let's restrict access to someone's email
You can get users emails by querying e.g. `users`, `userById`, and other graphQL queries
> Restrict access to email field

- nexus/utils/userValidation.ts
Fallout from recently merged PR. That PR was created before we had circle auto-builds set up so this should be something that's easy to catch before merging.
> Allow for nulls in email/handle of validateUpdateUserMutationData.

- components/Dashboard/MyFeed/MyFeed.tsx
**Issue:** closes #372 
I added the dialect to the language dropdown for the feed as well in the "selected Languages" from the dropdown. It occurs to me that the postCard may need the dialect labeled as well. I wanted to check in about that before pushing that up (@robin-macpherson @Lanny).
I have not yet done any build (per the issues with nexus and windows), and if there are any problems with the circleci build, I will try and fix that with additional commits.
> Add dialect to filter dropdown

- components/InlineFeedbackPopover/index.tsx
Was never able to repro in local but looking at the stack trace I got the one time I could repro on prod I think this should fix it. The `popover-root` portal container appears to be null in some situations, so we need to handle that case instead of waving away the null case with a type assertion.
No migs
> Fix 404 on thread click

- components/Dashboard/Post/Post.tsx
- nexus/post.ts
**Issue:** closes #411 
User's aren't unable to publish their drafts.
This was due to looking for `args.languageId` instead of `originalPost.languageId` since languageId is not required in the `updatePost` mutation.
No migs.
> Fix "Publish Draft" Bug

- nexus/comment.ts
- nexus/utils/email.ts
See title, we were just passing the wrong user into "sendPostCommentNotification", seemingly a holdover from the previous "only notify the post author" implementation. Also slight copy change to that email to make it correct for non-post-authors
No migs.
> Fix issue where emails would always be sent to author of a post comment when a new one is made

- pages/_app.tsx
- pages/_document.tsx
Relates to #407 , core issue is `#popover-root` is not present when a thread is opened and it needs to be. It's unclear to me why that element doesn't get rendered sometimes, but it seems to also affect `<ToastContainer>` (also in `_app.tsx`) but not `#modal-root` (in `_document.tsx`) so let's just try moving lifting it up out of `_app.tsx` and see what happens
> Move #popover-root to _document.tsx

- nexus/user.ts
**Issue:** closes #421 
A surprising number of users have been confused into thinking there was a major bug with our app because they were either accidentally clicking sign up twice or using a handle that was unavailable, because we were showing them the unique constraint DB error.
This PR adds a couple of checks to handle those errors better.
> Make Sign Up Errors More User Friendly

- README.md
Request to update the `README.md` documentation to reflect recent changes to prisma implementation. Current language references the `prisma` directory as being directly in root, but it is actually under `j-db-client`. The instructions around the `.env` file were slightly confusing, so I cleaned those up as well to be a bit more straight forward.
Details of the issue mention being able to run commands from root as well as the `prisma` folder (which actually need to be run from `j-db-client`). While some of the npm scripts can run from root, I found `npm run migrate:up` had to be specifically run from the `j-db-client` folder. It would be nice to eliminate the need for the duplicated environment file, but I'm new to a lot of this and not quite sure how to make that work.
Documentation is at …
> Updated doc regarding recent prisma changes.

- .eslintrc.js
> chore(446): disable typescript-eslint/explicit-function-return-type

- hooks/useAutosavedState.ts
Possibly addresses #416, it looks like when we save a post we "reset" the autosaved values, meaning clear the storage and restore the value to the initial value. The problem with this is the "restore the value to the initial value" step causes a state change and makes us write the reset value back to the local storage, and depending on how much clock drift there is between the server and client it might or might not be considered the more "recent" save. At least that's the theory.
@rickyweb if you have the time it would be awesome if you could try to repro #416 on the preview env.
> Don't set a value when clearing autosave state.

- components/Dashboard/Settings/DetailsForm.tsx
- components/PostEditor/PostEditor.tsx
- generated/graphql.tsx
- graphql/user/initiateAvatarImageUpload.graphql
- hooks/useAvatarImageUpload.ts
- hooks/useImageUpload.ts
- hooks/usePostImageUpload.ts
- nexus/post.ts
- nexus/user.ts
- nexus/utils/index.ts
- nexus/utils/resolverUtils.ts
Adds support for multiple transform configurations, our second configuration is for avatar images. Previously we were reusing the post image config so we'd get a 1200px by something image which was wayyyy bigger than we'd ever present to the user. Now avatar uploads are 150px square. This should reduce the total network IO required to load the feed and comments, plus save us a little on S3 costs. Main goal here however is a PoC for multiple image transforms which will be necessary for inline images.
No migs
Related thumbbuster PR that needs to be deployed first: https://github.com/Journaly/thumbbuster/pull/1
> Avarar specific sizing

- packages/web/pages/_app.tsx
- packages/web/pages/_document.tsx
**Issue:** fixes #470 
Follows the advice in https://err.sh/next.js/no-document-viewport-meta that viewport meta tag should be in the `<Head>` component in `_app.js` and not `_document.js`.
No hay.
No hay.
> Fix Next.js Meta Tag Warning

- packages/web/generated/graphql.tsx
- packages/web/graphql/fragments.graphql
- packages/web/graphql/post/createPost.graphql
- packages/web/pages/dashboard/new-post.tsx
**Issue:** #496 
After creating a post as a draft or publishing it, the user will be able to see this one on the list of `My posts`
FYI: Instead of invalidating the query, I'm following the previous implementation of update the cache after receive a request success callback. With this approach, we can avoid an extra request.
component `packages/web/pages/dashboard/new-post.tsx` refactors:
> fix(496): add created post on cache

- packages/web/components/InlineFeedbackPopover/Comment.tsx
- packages/web/components/InlineFeedbackPopover/Thread.tsx
**Issue:** #434 
It will add an optimistic UI experience to the thanks on comments.
> FYI: Just made a re-research about the approach to update the cache data on the latest apollo client, was very unhappy with the last approach I used before using `cache. readQuery` and `cache. writeQuery` (used to use it in my previous experience with apollo-client ). Anyways, found this function `cache.modify` that definitely is very easy to implement and remove all that complexity adopted before.
> - https://www.apollographql.com/blog/first-impressions-with-apollo-client-3-2ae2a069ab2f/
> - https://www.apollographql.com/docs/react/caching/cache-interaction/#cachemodify
https://www.loom.com/share/2a4478d009304e5496193d7f3e77a45e
> feat(434): use optimistic thanks on comments

- packages/web/components/Dashboard/Post/Post.tsx
- packages/web/components/Dashboard/Post/helpers.ts
**Issue:** fixes #505 
Investigating it, saw that the feedback popover was being shown in the wrong position.
https://www.loom.com/share/78298707a4024d43872625575761fbfe
To fix it decided to get the element's coordinates related to the document.
FYI: current version gets the parent position
https://www.loom.com/share/d89ed30c28274abcb5691e1c209d683f
> bugfix(505): feedback thread position when opened in tables

- packages/web/lib/apollo.tsx
- packages/web/nexus/user.ts
This sets up GraphCDN in production!
Note that I had to explicitly set the domain on the session cookie, refer to that commit for more background on that. Other than that I just changed the URL Apollo Client is fetching from in production to the GraphCDN one!
**DO NOT MERGE THIS UNTIL YOU HAVE api.journaly.com SET UP!** Here's the two CNAME's you have to set to enable it:
```
FROM: _acme-challenge.api.journaly.com 
TO: nbklcf9uy4urmfcm9h.fastly-validations.com
FROM: api.journaly.com
TO: ecp.map.fastly.net
```
**Issue:** N/A
Journaly.com profile url (include if you'd like the "code contributor" badge): https://journaly.com/dashboard/profile/5638
> Set up GraphCDN

- packages/web/lib/apollo.tsx
- packages/web/nexus/user.ts
Reverts Journaly/journaly#510
`GET https://www.googletagmanager.com/gtag/js?id=UA-162783279-1 net::ERR_BLOCKED_BY_CLIENT`
`Access to fetch at 'https://api.journaly.com/' from origin 'https://journaly.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
`POST https://api.journaly.com/ net::ERR_FAILED`
> Revert "Set up GraphCDN"

- packages/web/components/JournalyEditor/JournalyEditor.tsx
- packages/web/components/JournalyEditor/RenderElement.tsx
- packages/web/components/JournalyEditor/helpers.ts
Mainly fixes issues with inline images, namely the inability to move the cursor past an inline image when it's at the end of the document, and adds some visibility into when the image is "selected" (meaning the cursor is on it). But also: Fixes #547 while we're here.
No migs
> Inline image misc fixes

- packages/web/components/Dashboard/Profile/ProfileStats.tsx
- packages/web/generated/graphql.tsx
- packages/web/graphql/user/userStats.graphql
- packages/web/public/static/locales/en/profile.json
- packages/web/resolvers/user.ts
**Issue:** #567
Includes post comments and thread comments in activity graph on profile/stats page, with toggles to select which sorts of activities are included in the graph
No DB changes, as before the stats query is ad-hoc
> Comments in activity graph

- packages/web/components/JournalyEditor/Toolbar/Toolbar.tsx
**Issue:** fixes #586 
The toolbar ended up with appearing as transparent when floating above elements and was actually behind them making it also unclickable.
This PR simply sets the z-index to `1` which appears to be sufficient.
No migs
(See issue for original problem)
> Fix J-Editor Toolbar Transparency Bug

- packages/j-mail/package-lock.json
- packages/j-mail/package.json
Upgrade typescript for j-mail and ensure prisma:generate runs before a deploy.
> [j-mail] Add prisma as a direct dep and upgrade typescript to 4.x

- packages/j-mail/src/emails/updateEmail.ts
- packages/j-mail/src/handler.ts
- packages/j-mail/src/utils.ts
- packages/web/components/Dashboard/Post/Post.tsx
- packages/web/components/PostEditor/PostEditor.tsx
- packages/web/generated/graphql.tsx
- packages/web/graphql/post/updatePost.graphql
- packages/web/pages/post/[id]/edit.tsx
- packages/web/resolvers/post.ts
Presence of `id` and `__typename` were throwing gql for a loop when saving a post without changing the headline image.
> Ensure no extra fields show up when saving a post with an existing image

- packages/web/components/PostBodyStyles/PostBodyStyles.tsx
- packages/web/pages/post/[id]/index.tsx
On laptop resolutions (wide, limited vertical resolution) images could end up occupying more the the full view port, this PR limits the vertical size of an image to 75% of the VP height. 
@robin-macpherson you mentioned that you thought it was going to be more complicated than this, but just a simple limit on vertical size seems to work. Some screenshots below. Let me know if any of these seem off.
Also removes layout padding on posts which I think gives post bodies some needed additional real estate
Posts with layout padding (existing):
Without layout padding (proposed):
Vertical size limiting:
> Set max vert size on inline images

- packages/web/components/Dashboard/MyFeed/MyFeed.tsx
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/pages/dashboard/my-feed.tsx
**Issue:** closes #490 
Builds a mechanism using cookies so that a user's search filters persist throughout and across sessions.
Cookies were used due to SSR.
No migs
Nada
> Preserve User's Search Filters With Cookies

- packages/web/components/Dashboard/Post/Post.tsx
Visual fix for 3 post controls on mobile and change to not render bump CTA on unpublished posts.
No migs, UI only
> Bump post minor followups

- packages/j-db-client/package.json
- packages/j-db-client/prisma/migrations/20210612192514_add_odradek_and_necromancer_badges/migration.sql
- packages/j-db-client/prisma/schema.prisma
- packages/j-mail/package-lock.json
- packages/j-mail/package.json
- packages/web/components/Badge/Badge.tsx
- packages/web/generated/graphql.tsx
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/public/static/locales/en/common.json
- packages/web/resolvers/comment.ts
- packages/web/resolvers/post.ts
- packages/web/resolvers/utils/email.ts
- packages/web/resolvers/utils/index.ts
Closes #433
Adds a badge ("Necromancer", which is terminology borrowed from SO. I couldn't think some something concise and better) that is assigned when leaving feedback on a post authored by someone else that's over a week old.
Also adds an easter egg badge that's assigned for saving a post without any edits.
One mig, low risk as all it does is expand an enum
> Old post feedback badge

- packages/web/generated/graphql.tsx
- packages/web/graphql/pages/postPage.graphql
- packages/web/resolvers/post.ts
Fixes bugs with post bumping.
If your PR doesn't involve any changes to the database, you can delete this section. If it does, briefly describe how it needs to be applied. Some common things you might mention are:
- Does the migration need to be applied before or after deploying code?
- Is applying the migration going to necessitate downtime?
- Is there any SQL or backfill logic that has to be run manually?
- Are the DB changes high risk in your estimation? Should a manual DB snapshot be taken before applying?
> Post Bumping - More Followups

- README.md
- packages/web/package.json
**Issue:** None
Update the `db:seed` command to set the `SNAPSHOT_FILE` variable to `seed.sql` and not `snapshot.sql`. Update the README for clarity & accuracy.
Journaly.com profile url (include if you'd like the "code contributor" badge):
> Fix database seed command

- packages/web/components/InlineFeedbackPopover/Comment.tsx
- packages/web/public/static/locales/en/comment.json
**Issue:** #512
I added a non-clickable like icon to the user's own inline comments, if the comment has at least one like.
I thought it looked too busy to put the icon side-by-side with the edit/delete icons, so I placed it above. It was a bit tricky to get the CSS right, and there might be a better way that doesn't result in so many new CSS classes.
Journaly.com profile url (include if you'd like the "code contributor" badge): https://journaly.com/dashboard/profile/8654
Short comment with likes:
Long comment with likes:
A comment without any likes appears the same as before:
> Display number of likes in a user's own comments

- packages/web/components/Dashboard/Post/Post.tsx
- packages/web/components/Dashboard/Post/helpers.ts
- packages/web/public/static/locales/en/post.json
**Issue:** closes #631 
One potential issue with my code is that it was quite messy to put the type of the `claps` array in `helpers.ts`. I couldn't figure out a better way (the type checker didn't like the `PostClap` type), but if there is one, please let me know!
> Show a tooltip with the specific users who clapped for a post

- packages/web/package-lock.json
- packages/web/package.json
**Issue:** closes #425 
Yesterday we merged in #635 but found a pretty disruptive bug in production where `getInitialProps` was exhibiting some strange behaviour (seeming to only return partial results for our translation JSON files) resulting in the Dashboard mainly just showing the i18n keys/labels and not the translation strings. This appeared to be due to some version bumps we got down the dependency tree in the `package-lock.json` file related to Next.js. I find that quite concerning and would like to investigate more, but for now found that simply pinning `Next` in our `package.json` did the trick so that we can at least release the feature.
No migs
> Add Markdown Support For Comments - Take 2

- packages/web/components/Dashboard/Post/PostComment.tsx
- packages/web/components/InlineFeedbackPopover/Comment.tsx
- packages/web/package-lock.json
- packages/web/package.json
Users seem to be loving the new Markdown support which is **great!**
- This PR adds the `remark-gfm` package which can be used as a plugin with `react-markdown` and adds support for strikethroughs, which I think are **super** helpful on Journaly for indicating deletions, and also seems to handle *some* new line scenarios better (after a block quote, the new line no longer gets eaten).
- Also adds some missing styles so that links are now properly visible, numbered lists are numbered, and improves a bit of spacing on block quotes
- Due to version issues we're experiencing with Next.js, I've had to use an older but still recent version of `react-markdown` and also an older version of `remark-gfm`. I've included a TODO to update these as soon as we figure out our Next versioning issues which …
> Increase Comment Markdown Support & Add Missing Styles

- packages/web/resolvers/subscription.ts
**Issue:**
- fixes #694 
Fixes the call site of `setPaymentMethod` within the `updateSubscriptionPaymentMethod` resolver where we were passing through a subscription ID instead of a customer ID.
No migs.
> Payments: Update Payment Method Improvement

- packages/web/pages/dashboard/new-post.tsx
Having 5 default post images definitely helped a TON with keeping the feed nice and fresh, but we do still often end up with a couple of posts back-to-back having the same image, sometimes multiple times on one page of the feed.
This PR adds one more default post image, just to give us that tiny bit extra diversity on the feed and also to keep things fresh for users who have gotten used to the other five 😊
> Add New Default Post Image

- packages/web/components/NotificationFeed/Notifications.tsx
**Issue:**
- Fixes #736 
Fixes an issue where a user deletes a comment that has a thanks attached to it. Solution is to use the top-level `triggeringUser` field instead for `thanksAuthor` and then null check.
No migs
N/A
> 🔧  Fix In-App Notifications Bug: Deleting A Comment With A Thanks

- packages/web/components/Dashboard/Post/PostComment.tsx
- packages/web/components/Dashboard/Post/PostComments.tsx
- packages/web/components/EditableMarkdown/EditableMarkdown.tsx
- packages/web/components/EditableMarkdown/index.ts
- packages/web/components/InlineFeedbackPopover/Comment.tsx
Changes to thread/post comments:
- Better visual separation of paragraphs in multi-paragraph post/thread comments:
- Reduces the space between lines of a paragraph 
- Increases the space between paragraphs
- Creates a new component that encapsulates presentation and editing markdown comments
- This also adds the "focus edit textarea on edit" behavior to post comments to make it consistent with thread comments
No migs
Before:
After:
> Better paragraph formatting for comments

- packages/web/resolvers/post.ts
**Issue:**
- Fixes #660 
- Related to #604 
Fixes issue in resolver where unauth'd user could not use the `posts` query, despite that query being designed for both auth'd and unauth'd cases.
No migs
> Allow unauth'd users to view profile pages

- packages/web/resolvers/comment.ts
Fixes an issue that surfaced where notifications weren't being created for comments in a newly opened thread after the optimizations we made in #728 .
Solution was to refetch the subscriptions after the upsert creating the new subscription and before creating the notifications - as the notifications were being created based on the outdated thread subscriptions.
- [N/A] 🚨 Publish new j-db-client version and update in both `web` and `j-mail`
- [N/A] 🚨 Deploy migs to stage
- [N/A] 🚨 DEPLOY `j-mail` to stage
- [N/A] 🚨 Deploy migs to prod
- [N/A] 🚨 DEPLOY `j-mail` TO PROD
None
None
> Fix Notification Creation On New Thread Creation

- packages/web/components/Dashboard/Profile/ProfileCard.tsx
- packages/web/generated/graphql.tsx
- packages/web/graphql/pages/profilePage.graphql
- packages/web/public/static/locales/de/profile.json
- packages/web/public/static/locales/en/profile.json
- packages/web/public/static/locales/es/profile.json
- packages/web/public/static/locales/it/profile.json
- packages/web/public/static/locales/zh_CN/profile.json
- packages/web/public/static/locales/zh_TW/profile.json
**Issue:**
- closes #606 
Final major improvements to the Journaly "following experience" by:
1. Enabling users to see how many Journalers are following them and they are following
2. Enabling users to see a complete list for each category
- We did decide to keep this information for each user private, in accordance with our UX design philosophy and values of not building features that promote the kind of behaviour that many other social platforms do that can be negative longterm for the actual users (in this case, promoting the desire to chase more followers).
No miggies
> 🔎 Display Follower & Following Stats On Journaler's Own Profile

- packages/web/package-lock.json
- packages/web/package.json
Just keeping Slate up-to-date as much as possible in light of recent reports.
> Update `slate-react` To 0.72.7

- packages/web/resolvers/post.ts
At 10:30pm U.K. time on Jan 28th we started getting reports of outages that revealed a concerning pattern where the DB was continuously but intermittently having problems. This PR is to test eliminating what appears to be by far the slowest query (and happens to be one of the least critical to User Experience and application functionality) to see if this resolves the outage.
None
N/A
> 📉 Eliminate Slowest Query - Outage Resolution

- packages/web/resolvers/post.ts
Reverts Journaly/journaly#770
While experiencing some puzzling outages yesterday we tried removing our most expensive query to test the impact, but we finally understood that these outages appeared to actually be due to some connectivity issues between Vercel and the DB... another catalyst to move off of Vercel and manage our deployment system internally at last.
Reverting that change.
> Revert "📉 Eliminate Slowest Query - Outage Resolution"

- packages/web/components/JournalyEditor/JournalyEditor.tsx
- packages/web/hooks/useAutosavedState.ts
Eliminate second render introduced by restoring `useAutosaveState` and fix autosave state by not even trying to SSR the editor.
Fixes #755
Either some change in slate or unfortunate interaction of slate-plugins/plate and slate caused slate to fail to update DOM state when a new `value` prop is passed to slate-react's `Slate` component, which broke autosaving (strictly speaking autosaving always worked fine, but slate just wouldn't reflect a restored value correctly, which you could observe with e.g. post titles saving and restoring correctly). To fix this we need to make sure that slate has the autosaved value available on its very first render. Further the DOM state of the editor must be equal during SSR and on the first render in the client or else slate explodes. To make this work, …
> Fix autosave

- packages/web/components/Modal/ModalBody.tsx
- packages/web/components/Modal/ModalHeader.tsx
- packages/web/components/UserList/UserList.tsx
**Issue:**
- #785 
Our `<Modal>` component was built quite quickly very early on when we only really had one use case (gathering a user's language info when first signing up), but especially as we've expanded its use throughout the app, I've always felt like it needed a nice little design makeover. In particular the typography and spacing didn't feel right, so this PR makes the following improvements:
- Switches the font-family over to our sans-serif typeface
- Improves the spacing by removing the unnecessary huge amount of padding at the top when the header title isn't being shown
- Also reduces padding at the sides and bottom of the modal body to make things feel more balanced and spacious
- Centers title text
I think even this very simple change makes a big difference and the modal …
> 📐 Modal Design Improvements ✐

- packages/web/components/Modals/ImageUploadModal/SearchUnsplash.tsx
Changes unsplash image search results to distribute the width of the row between images in it so images well take up and previously occupied space in proportion to their aspect ratio. Also reduced space between images both vertically and horizontally, and added a small border radius to images to make them a little less "sharp" as we generally avoid hard 90deg edges elsewhere.
No Migs
Before: 
After:
> Full-justify rows of unspash images and condense layout a little bit.

- packages/web/components/Dashboard/Post/Post.tsx
- packages/web/components/Icons/ReportSpamFlagIcon.tsx
- packages/web/components/Modals/ConfirmationModal/ConfirmationModal.tsx
- packages/web/generated/graphql.tsx
- packages/web/graphql/post/reportSpamPost.graphql
- packages/web/public/static/locales/de/post.json
- packages/web/public/static/locales/en/post.json
- packages/web/public/static/locales/zh_CN/post.json
- packages/web/public/static/locales/zh_TW/post.json
- packages/web/resolvers/post.ts
- packages/web/resolvers/utils/email.ts
**Issues:**
- closes #818 
This PR builds a simple mechanism for users to report spam posts directly from a post with just two clicks. It introduces a new "Report Spam" icon/button at the bottom of a post, which opens a confirmation modal. Upon confirmation, an email is sent to the Journaly Customer Support inbox with the data needed to remove the post and - if needed - its author.
No migs!
**1. New Report Spam Button**
**2. New Report Spam Modal**
**3. Success Toast**
**4. The Spam Report Email**
> 🚩 FEATURE: "Report Spam" Button on Posts 🚫

- packages/jadmin/jadmin.js
When testing out our new spam user deletion script, it looks like none of our test users had `SocialMedia` records.
This PR just adds in an extra `DELETE` clause to handle that.
N/A
N/A
> Add Missing DELETE Clause for User Deletion Script

- packages/jadmin/jadmin.js
**Issue:** 
* closes #828 
In #824 we added a script that deletes a user (intended for those who brazenly violate our Terms of Service) and all related records. There are some cases where we may want to delete only a post, so this PR adds a script to handle that.
N/A
N/A
> Add new Jadmin script for deleting a post

- packages/web/components/Dashboard/Filters/Filters.tsx
- packages/web/components/Dashboard/MyFeed/MyFeed.tsx
**Issue:**
- fixes: #738 
* Ensures that setting, unsetting, or changing any filters resets the pagination.
* Refactors some filter-related functions to make sure that they are all defined functions with `useCallback()`
No hay migs!
N/A
> 🐞🔧 Fix Filter-Pagination-Reset Bug & Some Refactoring/Improvements

- packages/web/components/AuthGate/AuthGate.tsx
**Issue:**
* Fixes #843 
* Fixes #604 
We did it! Finally figured out what in the world was going on where a decent number of people were ending up on an exploding server/Vercel error page after clicking the link to verify their email address.
In the end, the issue lay within `<AuthGate>` where we were only null-checking the `currentUser` on the client, but not on the server. This meant that if someone went to any AuthGated page while not being logged in, things would explode spectacularly and instead of our own client-side error page and message, we were getting the Vercel page due to this occurring on the server.
We believe the User Behavior Pattern that would cause this is a user signing up on their laptop/computer, and then clicking the verification link on their phone.
This also …
> 💥 FINALLY Fix Exploding Email Verification User Experience ✅

- packages/web/components/Dashboard/MyFeed/FeedHeader.tsx
As a part of the project to switch our language lists back to using the English names of each language for now, a small update to (simplify) make the greeting code always just use the `name` field instead of using `devName` by default.
This is because I have now switched the columns so that `name` is the English word for the language and `devName` contains the Endonym.
> Update `My Feed` Greetings To Use `name` by default

- packages/web/components/FeatureComparisonTable/FeatureComparisonTable.tsx
- packages/web/components/Site/Home/FeatureSection.tsx
- packages/web/components/Site/Home/Home.tsx
- packages/web/components/Site/Home/TopSection.tsx
- packages/web/public/static/locales/de/common.json
- packages/web/public/static/locales/de/settings.json
- packages/web/public/static/locales/en/common.json
- packages/web/public/static/locales/en/settings.json
- packages/web/public/static/locales/es/common.json
- packages/web/public/static/locales/it/common.json
- packages/web/public/static/locales/it/settings.json
- packages/web/public/static/locales/pt_BR/common.json
- packages/web/public/static/locales/pt_BR/settings.json
- packages/web/public/static/locales/zh_CN/common.json
- packages/web/public/static/locales/zh_CN/settings.json
- packages/web/public/static/locales/zh_TW/common.json
- packages/web/public/static/locales/zh_TW/settings.json
**Issues:**
* closes #848 
* closes #849 
This PR makes a really nice improvement to the landing page by finally showcasing our amazing (and growing!) feature set so that users can see all the things we offer before signing up.
It also adds some new items to the `<FeatureComparisonTable />` making that more attractive too!
No hay
**Before**
**After**
> 📐✍🏼 Design Improvements To Landing Page & Updated Feature Table

- packages/j-db-client/prisma/migrations/20230709145546_index_user_handle_trigram/migration.sql
- packages/web/resolvers/user.ts
Add an index on user handles, and an arg to the `users` query to allow "fuzzy" searching by user handle
**Issue:** <#issue>
...
Journaly.com profile url (include if you'd like the "code contributor" badge):
If your PR doesn't involve any changes to the database, you can delete this section. If it does, briefly describe how it needs to be applied. Some common things you might mention are:
- Does the migration need to be applied before or after deploying code?
- Is applying the migration going to necessitate downtime?
- Is there any SQL or backfill logic that has to be run manually?
- Are the DB changes high risk in your estimation? Should a manual DB snapshot be taken before applying?
> BE: user search

- packages/web/components/Dashboard/Nav/Nav.tsx
- packages/web/public/static/locales/de/common.json
- packages/web/public/static/locales/en/common.json
- packages/web/public/static/locales/es/common.json
- packages/web/public/static/locales/it/common.json
- packages/web/public/static/locales/pt_BR/common.json
- packages/web/public/static/locales/zh_CN/common.json
- packages/web/public/static/locales/zh_TW/common.json
- packages/web/theme/index.ts
We've known for a long time that one of the biggest blockers we have with Journaly Premium is ***VISIBILITY***: most people simply don't know it exists. Historically, we've been purposely shy with shouting about Premium, since we wanted to really have a great offering first.
I think at this point, we do have a good amount of Premium features, and we at least show the ones that are coming soon, with multiple **AWESOME** ones coming with the launch of Direct Messaging. But DMs will take some time, and it's really time for us to make a push to increase revenue – so I think it's time to experiment and simply try to see what happens if we really boost the visibility of Premium. After all, we do still have people who sign up, so in theory if we made sure all users knew about it, we should see …
> 🚀 EXPERIMENT: Boost Premium Visibility in Nav with "Go Premium" Badge/Button

- packages/web/components/Button/Button.tsx
- packages/web/components/Dashboard/Nav/Nav.tsx
- packages/web/components/JournalyEditor/Toolbar/Toolbar.tsx
- packages/web/components/Layouts/DashboardLayout.tsx
- packages/web/components/Modal/Modal.tsx
- packages/web/components/Modals/ImageUploadModal/SearchUnsplash.tsx
- packages/web/components/NavLink/NavLink.tsx
- packages/web/components/NotificationCount/NotificationCount.tsx
- packages/web/components/NotificationFeed/NotificationFeed.tsx
- packages/web/components/PostEditor/PostEditor.tsx
- packages/web/components/PostHeader/PostHeader.tsx
- packages/web/components/Select/Select.tsx
- packages/web/components/Site/Nav/Nav.tsx
- packages/web/components/SkipLink/SkipLink.tsx
- packages/web/components/SkipLink/index.ts
- packages/web/components/SwipeableElement/SwipeableElement.tsx
- packages/web/styles/globalStyles.css
- packages/web/theme/index.ts
point-by-point re: the email that spawned this effort:
>When I try to add a photo via Unsplash I don't seem to be able to access the tab. In the screencast attached, I'm tabbing repeatedly at a consistent speed but only the 'choose image to upload' and 'close' links are highlighted. After a bit of trial and error I think at one point I *can* hit return to access the 'search Unsplash' option but if the active element was always highlighted, this would be a piece of cake and one less barrier :)
Fixed, although the approach was to use an underline (same as the hover state) to signal focus on these links. I think the looks reasonable but maybe it's not super duper obvious. Open to considering a more visually impactful signal of focus if this doesn't work
>Similarly, when I'm on the New Post …
> A smorgasbord of a11y changes to nav and the new post page

- packages/j-db-client/prisma/migrations/20231019145738_create_notification_deletion_triggers/migration.sql
- packages/j-db-client/prisma/schema.prisma
**Issue:** <#issue>
..
If your PR doesn't involve any changes to the database, you can delete this section. If it does, briefly describe how it needs to be applied. Some common things you might mention are:
- Does the migration need to be applied before or after deploying code?
- Is applying the migration going to necessitate downtime?
- Is there any SQL or backfill logic that has to be run manually?
- Are the DB changes high risk in your estimation? Should a manual DB snapshot be taken before applying?
> 🥍🐞 Fix Toxic Notification Bug: Create DB Function & Triggers To Clean Up Empty Nester `InAppNotification` Records

- packages/web/components/EditableMarkdown/EditableMarkdown.tsx
**Issue:**
* Fixes #883 
This PR makes sure that the text inside of a suggestion block wraps correctly, if the highlighted and/or suggested text is wider than the popover component.
N/A
**BEFORE - User Report:**
**AFTER:**
> 🐞 Suggestions: Make The Suggested Text Wrap

- packages/jadmin/jadmin.js
Adds the Jadmin command used to backfill our Moosend email list after fixing the bug with email verification.
> 🐄 📧 Add Moosend Backfill Jadmin Command

- packages/j-db-client/package.json
- packages/j-db-client/prisma/migrations/20240822150636_add_posting_ip_to_posts_and_comments/migration.sql
- packages/j-db-client/prisma/schema.prisma
- packages/j-mail/package.json
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/resolvers/comment.ts
- packages/web/resolvers/context.ts
- packages/web/resolvers/post.ts
- packages/web/resolvers/utils/getPostingIpAddress.ts
- packages/web/resolvers/utils/index.ts
For security and moderation purposes, we are going to start storing the IP address of the author of posts and comments.
This will allow us to identify particular users who engage in behavior that harms other users and potentially create multiple accounts.
This will also allow us to implement IP Blocking, should those users need to be banned from the platform.
- Does the migration need to be applied before or after deploying code? **Before**
- Is applying the migration going to necessitate downtime? **Negative**
- Is there any SQL or backfill logic that has to be run manually? **Negativo**
- Are the DB changes high risk in your estimation? Should a manual DB snapshot be taken before applying? **These should be low risk. It's a new, nullable field.**
The following screenshot shows one new …
> 🛜 Implement Solution For Storing Post & Comment Author's IP Address in Respective Tables
